# Generated by Django 2.2 on 2020-09-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Компания')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронная почта')),
                ('telephone', models.IntegerField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'О предприятии',
            },
        ),
        migrations.CreateModel(
            name='CompanyUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название подразделения')),
                ('full_name', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Полное название подразделения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Company', verbose_name='Предприятие')),
            ],
            options={
                'verbose_name': 'Название подразделения',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название депо')),
                ('director', models.CharField(max_length=200, verbose_name='директор')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Название депо',
                'verbose_name_plural': 'Названия депо',
            },
        ),
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic', models.CharField(max_length=20, null=True, unique=True, verbose_name='график')),
            ],
            options={
                'verbose_name': 'Вид графика',
                'verbose_name_plural': 'виды графиков',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='должность')),
            ],
            options={
                'verbose_name': 'должность',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='пол')),
            ],
            options={
                'verbose_name': 'пол',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=100, null=True, unique=True, verbose_name='вид транспорта')),
            ],
            options={
                'verbose_name': 'Вид транспорта',
                'verbose_name_plural': 'виды транспорта',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=250, verbose_name='Ф.И.О.')),
                ('birthday', models.CharField(max_length=50, verbose_name='дата рождения')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='адрес')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cds.Position')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Sex', verbose_name='Пол')),
                ('working_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.CompanyUnit', verbose_name='место работы')),
            ],
            options={
                'verbose_name': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Номер маршрута')),
                ('start_point', models.CharField(default='', max_length=250, verbose_name='Начальная точка')),
                ('end_point', models.CharField(default='', max_length=250, verbose_name='Конечная точка')),
                ('time_route', models.IntegerField(default=0, verbose_name='Время оборотного рейса')),
                ('length_route', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='протяжённость')),
                ('dep_first_car_h', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='Выезд первого вагона часы')),
                ('dep_first_car_m', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='Выезд первого вагона минуты')),
                ('arr_last_car_h', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='Заезд последнего вагона часы')),
                ('arr_last_car_m', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='Заезд последнего вагона минуты')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Depot', verbose_name='Название депо')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрут',
            },
        ),
        migrations.CreateModel(
            name='RollingStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour_of_day', models.TimeField(verbose_name='начальное время суток')),
                ('num_car', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='количество подвижного состава')),
                ('start_data', models.DateField(verbose_name='Начальная дата')),
                ('end_data', models.DateField(verbose_name='конечная дата')),
                ('end_hour_of_day', models.DateField(verbose_name='конечное время суток')),
                ('graphic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Graphic', verbose_name='график')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Route', verbose_name='Номер маршрута')),
            ],
            options={
                'verbose_name': 'расстановка подвижного состава',
                'verbose_name_plural': 'расстановки подвижного состава',
            },
        ),
        migrations.AddField(
            model_name='depot',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Transport', verbose_name='Вид транспорта'),
        ),
    ]
