# Generated by Django 2.2 on 2020-07-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Компания')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронная почта')),
                ('telephone', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'О предприятии',
            },
        ),
        migrations.CreateModel(
            name='CompanyUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название подразделения')),
                ('full_name', models.TextField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Company', verbose_name='Предприятие')),
            ],
            options={
                'verbose_name': 'Название подразделения',
            },
        ),
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic', models.CharField(max_length=20, null=True, verbose_name='график')),
            ],
            options={
                'verbose_name': 'Вид графика',
                'verbose_name_plural': 'виды графиков',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='должность')),
            ],
            options={
                'verbose_name': 'должность',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='пол')),
            ],
            options={
                'verbose_name': 'пол',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=100, null=True, verbose_name='вид транспорта')),
            ],
            options={
                'verbose_name': 'Вид транспорта',
                'verbose_name_plural': 'виды транспорта',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=250, verbose_name='Ф.И.О.')),
                ('birthday', models.DateField(verbose_name='дата рождения')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='адрес')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cds.Position')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Sex', verbose_name='Пол')),
                ('working_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.CompanyUnit', verbose_name='место работы')),
            ],
            options={
                'verbose_name': 'сотрудники',
            },
        ),
    ]
