# Generated by Django 2.2 on 2020-09-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='transport',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cds.Transport', verbose_name='Вид транспорта'),
            preserve_default=False,
        ),
    ]
