# Generated by Django 2.2 on 2020-07-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.IntegerField(max_length=15, verbose_name='Телефон'),
        ),
    ]
