# Generated by Django 2.2 on 2020-09-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstock',
            name='published',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата отчёта'),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='end_hour_of_day',
            field=models.TimeField(verbose_name='конечное время суток'),
        ),
    ]
