# Generated by Django 2.2 on 2020-09-12 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0002_auto_20200912_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstock',
            name='transport',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cds.Transport', verbose_name='Вид транспорта'),
            preserve_default=False,
        ),
    ]
