# Generated by Django 2.2 on 2020-09-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0002_route_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='transport',
        ),
    ]
