# Generated by Django 2.2 on 2020-08-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0003_auto_20200712_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyunit',
            name='full_name',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Полное название подразделения'),
        ),
    ]
