# Generated by Django 2.2 on 2020-09-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0003_rollingstock_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstock',
            name='depot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cds.Depot', verbose_name='Депо'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Transport', verbose_name='Транспорт'),
        ),
    ]
