# Generated by Django 2.2 on 2020-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0004_auto_20200806_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.CharField(max_length=50, verbose_name='дата рождения'),
        ),
    ]
