# Generated by Django 2.2 on 2020-09-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0005_auto_20200914_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollingstock',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='rollingstock',
            name='transport',
        ),
    ]
