# Generated by Django 2.2 on 2020-08-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0005_auto_20200809_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='graphic',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='график'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='вид транспорта'),
        ),
    ]
