# Generated by Django 2.2 on 2020-09-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0007_auto_20200924_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollingstock',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='rollingstock',
            name='transport',
        ),
    ]
