# Generated by Django 2.2 on 2020-08-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0008_auto_20200809_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollingStockFormTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_route', models.IntegerField(max_length=2, unique=True, verbose_name='номер маршрута')),
                ('start_point', models.CharField(max_length=250, verbose_name='Начальная точка')),
                ('end_point', models.CharField(max_length=250, verbose_name='Конечная точка')),
                ('time_route', models.IntegerField(max_length=3, verbose_name='Время оборотного рейса')),
                ('length_route', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='протяжённость')),
                ('dep_first_car', models.TimeField(verbose_name='Выезд первого вагона')),
                ('arr_last_car', models.TimeField(verbose_name='Заезд последнего вагона')),
            ],
            options={
                'verbose_name': 'Форма 2',
            },
        ),
        migrations.CreateModel(
            name='RollingStockFormThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour_of_day', models.TimeField(verbose_name='Время суток')),
                ('num_car', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='количество подвижного состава')),
                ('start_data', models.DateField(verbose_name='Начальная дата')),
                ('end_data', models.DateField(verbose_name='конечная дата')),
                ('end_hour_of_day', models.DateField(verbose_name='конечная дата')),
                ('route', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='маршрут')),
                ('graphic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Graphic', verbose_name='график')),
            ],
            options={
                'verbose_name': 'Форма 3',
            },
        ),
        migrations.CreateModel(
            name='RollingStockFormOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='адрес')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.CompanyUnit', verbose_name='название депо')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Worker', verbose_name='директор')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.Transport', verbose_name='вид транспорта')),
            ],
            options={
                'verbose_name': 'Форма 1',
            },
        ),
    ]
