# Generated by Django 2.2 on 2020-08-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0009_rollingstockformone_rollingstockformthree_rollingstockformtwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstockformtwo',
            name='number_route',
            field=models.IntegerField(unique=True, verbose_name='номер маршрута'),
        ),
        migrations.AlterField(
            model_name='rollingstockformtwo',
            name='time_route',
            field=models.IntegerField(verbose_name='Время оборотного рейса'),
        ),
    ]
